import {Space_Grotesk} from 'next/font/google'
import "./globals.css";
import NavBar from '@/components/utils/NavBar';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const spaceGrotesk = Space_Grotesk({
  subsets:['latin'],
  weight:["300","400","500","600","700"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
